### ISSUE TITLE
Bug on opening

### ISSUE THREAD

**Issue by MartyLake** [PrudentMe/main#2] opened 2019-09-12 21:07 UTC
Hello,
I have this error when opening the software:

> Error: ENOENT: no such file or directory, open './secret/verifier_key.pub.pem'

then

> Cannot verify this instance of Prudent.

then it closes.

What can I do about it? How can I help you to diagnose this further ?

Best

**Comment by vitoc** [comment] 2020-01-15 00:25
Hello @MartyLake Thanks! Sorry, I missed this earlier. This should be resolved in the latest release (R16). Please download and use that release instead. Do let me know if there's any issue.

**Comment by MartyLake** [comment] 2020-01-18 15:15
Hey,

New release displays "TypeError: Cannot read property 'toString' of undefined", then "Sorry, Prudent ran into a problem", then exit :'(

**Comment by vitoc** [comment] 2020-01-18 16:42
Thanks @MartyLake ! What OS are you using? macOS? If so, which version of macOS are you using? Is it Catalina? Had you installed any Prudent extension before? Trying to reproduce the error above!

**Comment by MartyLake** [comment] 2020-01-18 16:49
I'm on windows 10. Never installed any extension as the vanilla was already crashing. Maybe it has to do with my ledger file, but I am reluctant of sharing it :/

**Comment by dlsmartins** [comment] 2020-01-20 09:38
I've got exactly the same isue - "TypeError: Cannot read property 'toString' of undefined", then "Sorry, Prudent ran into a problem" on opening. I'm on Win10 too.

**Comment by vitoc** [comment] 2020-01-20 10:39
Thanks @MartyLake @dlsmartins Please try [release 17](https://github.com/PrudentMe/main/releases/tag/17) Should be fixed!

**Comment by dlsmartins** [comment] 2020-01-20 10:49
Thanks @vitoc. The TypeError has indeed been fixed, but only to be replaced by a "Analytics server error" :/

**Comment by vitoc** [comment] 2020-01-21 10:18
Sorry @dlsmartins ! This is a little tougher to debug as I cannot reproduce this. Are you getting the same error all the time or is it intermittent? You will need to have an internet connection to get to the analytics server. Anyway, I'd made another release that gives finer error messages. Would you be so kind as to help give this a shot again and report back with the new error message (if any)? :)

**Comment by dlsmartins** [comment] 2020-01-21 10:43
> Sorry @dlsmartins ! This is a little tougher to debug as I cannot reproduce this. Are you getting the same error all the time or is it intermittent? You will need to have an internet connection to get to the analytics server. Anyway, I'd made another release that gives finer error messages. Would you be so kind as to help give this a shot again and report back with the new error message (if any)? :)

I've installed R18. Exactly the same error? What is the analytics server exactly? And why connecting to it would be required for this to work?

**Comment by MartyLake** [comment] 2020-01-21 23:21
Same error, but not crashing after dismissing it. Closing and opening again and the error does not appear again.

Now it's more about the latency/speed of the software but I guess this issue it not meant for that.

**Comment by vitoc** [comment] 2020-01-22 18:10
Thanks @MartyLake ! I guess you are referring to the speed in which the figures in the "financial" calendar renders. Will try and see if I can use a different approach as the current one calls ledger-cli quite a lot of times for each month and year. @dlsmartins The analytics server helps let me know anonymously that there are people actually using this. Keeps a count to keep me motivated!

**Closed** 2020-12-27 03:23 UTC
